---
- name: Verify errors scenario
  hosts: all
  gather_facts: true
  become: true
  vars:
    osbuild_worker_config_dir: /etc/osbuild-worker

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check that osbuild-composer-worker is not installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['osbuild-composer-worker'] is not defined

    - name: Stat osbuild_worker_config_dir
      ansible.builtin.stat:
        path: "{{ osbuild_worker_config_dir }}"
      register: osbuild_worker_config_dir_stat

    - name: Check that osbuild_worker_config_dir does not exist
      ansible.builtin.assert:
        that:
          - not osbuild_worker_config_dir_stat.stat.exists
