---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "osbuild-worker-${image:-fedora}-${tag:-latest}"
    image: "${namespace:-quay.io/fedora}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
    privileged: true
    additional_packages: "${additional_packages:-''}"
provisioner:
  name: ansible
verifier:
  name: ansible
