---
- name: Verify default scenario
  hosts: all
  gather_facts: true
  become: true
  vars:
    osbuild_worker_config_dir: /etc/osbuild-worker
    osbuild_worker_config_dir_mode: '0755'
    osbuild_worker_config_file: "{{ osbuild_worker_config_dir }}/osbuild-worker.toml"
    osbuild_worker_config_file_mode: '0644'
    osbuild_worker_remote_worker_service_name: "osbuild-remote-worker@{{ test_osbuild_worker_server_hostname }}.service"
    osbuild_worker_secrets_mode: '0400'

  tasks:
    - name: Include common variables
      ansible.builtin.include_vars:
        file: defaults/main.yml

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check that osbuild-composer-worker is installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['osbuild-composer-worker'] is defined

    - name: Stat osbuild_worker_config_dir
      ansible.builtin.stat:
        path: "{{ osbuild_worker_config_dir }}"
      register: osbuild_worker_config_dir_stat

    - name: Check that osbuild_worker_config_dir exists
      ansible.builtin.assert:
        that:
          - osbuild_worker_config_dir_stat.stat.exists
          - osbuild_worker_config_dir_stat.stat.isdir
          - osbuild_worker_config_dir_stat.stat.mode == osbuild_worker_config_dir_mode

    - name: Stat osbuild_worker_config_file
      ansible.builtin.stat:
        path: "{{ osbuild_worker_config_file }}"
      register: osbuild_worker_config_file_stat

    - name: Check that osbuild_worker_config_file exists
      ansible.builtin.assert:
        that:
          - osbuild_worker_config_file_stat.stat.exists
          - osbuild_worker_config_file_stat.stat.isreg
          - osbuild_worker_config_file_stat.stat.mode == osbuild_worker_config_file_mode

    - name: Check status of osbuild remote worker service
      ansible.builtin.systemd:
        name: "{{ osbuild_worker_remote_worker_service_name }}"
      register: osbuild_remote_worker_service

    - name: Check that osbuild remote worker service is enabled and started
      ansible.builtin.assert:
        that:
          - osbuild_remote_worker_service.status['LoadState'] == 'loaded'
          - osbuild_remote_worker_service.status['ActiveState'] == 'active'
          - osbuild_remote_worker_service.status['UnitFileState'] == 'enabled'

    - name: Get journal log for worker service
      ansible.builtin.command: journalctl -u "{{ osbuild_worker_remote_worker_service_name }}" --no-pager
      changed_when: false
      register: osbuild_remote_worker_service_journal

    - name: Count how many times osbuild remote worker service was started
      ansible.builtin.set_fact:
        osbuild_remote_worker_service_starts: "{{ osbuild_remote_worker_service_journal.stdout_lines | \
          select('search', 'Started ') | list | count }}"

    - name: Check that osbuild remote worker service started only once
      ansible.builtin.assert:
        that:
          - osbuild_remote_worker_service_starts | int == 1
        fail_msg: "osbuild remote worker service was started {{ osbuild_remote_worker_service_starts }} times
          but it should be started only once"

    - name: Fetch the content of osbuild worker config file (Base64 encoded)
      ansible.builtin.slurp:
        src: "{{ osbuild_worker_config_file }}"
      register: osbuild_worker_config_file_content_encoded

    - name: Register (raw) content of osbuild worker config file as a variable
      ansible.builtin.set_fact:
        osbuild_worker_config_file_content: "{{ osbuild_worker_config_file_content_encoded.content | b64decode }}"

    - name: Check the worker config file
      ansible.builtin.assert:
        that:
          - auth_config_part in osbuild_worker_config_file_content
          - osbuild_worker_config_file_content is not match(".*base_path = .*")
          - osbuild_worker_config_file_content is not match(".*offline_token = .*")
          - osbuild_worker_config_file_content is not match(".*\[aws\].*")
          - osbuild_worker_config_file_content is not match(".*\[azure\].*")
          - osbuild_worker_config_file_content is not match(".*\[gcp\].*")
          - osbuild_worker_config_file_content is not match(".*\[koji.+\].*")
      vars:
        auth_config_part: |-
          [authentication]
          oauth_url = "{{ test_osbuild_worker_authentication_oauth_url }}"
          client_id = "{{ test_osbuild_worker_authentication_client_id }}"
          client_secret = "{{ osbuild_worker_config_dir }}/client_secret"

    - name: Stat client_secret file
      ansible.builtin.stat:
        path: "{{ test_osbuild_worker_client_secret_file_path }}"
      vars:
        test_osbuild_worker_client_secret_file_path: "{{ osbuild_worker_config_dir }}/client_secret"
      register: client_secret_file_stat

    - name: Check that client_secret file exists on the remote host
      ansible.builtin.assert:
        that:
          - client_secret_file_stat.stat.exists
          - client_secret_file_stat.stat.isreg
          - client_secret_file_stat.stat.mode == osbuild_worker_secrets_mode
