---
- name: Verify default extended scenario
  hosts: all
  gather_facts: true
  become: true
  vars:
    osbuild_worker_config_dir: /etc/osbuild-worker
    osbuild_worker_config_dir_mode: '0755'
    osbuild_worker_config_file: "{{ osbuild_worker_config_dir }}/osbuild-worker.toml"
    osbuild_worker_config_file_mode: '0644'
    osbuild_worker_remote_worker_service_name: "osbuild-remote-worker@{{ test_osbuild_worker_server_hostname }}.service"
    osbuild_worker_secrets_mode: '0400'

  tasks:
    - name: Include common variables
      ansible.builtin.include_vars:
        file: defaults/main.yml

    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check that osbuild-composer-worker is installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['osbuild-composer-worker'] is defined

    - name: Stat osbuild_worker_config_dir
      ansible.builtin.stat:
        path: "{{ osbuild_worker_config_dir }}"
      register: osbuild_worker_config_dir_stat

    - name: Check that osbuild_worker_config_dir exists
      ansible.builtin.assert:
        that:
          - osbuild_worker_config_dir_stat.stat.exists
          - osbuild_worker_config_dir_stat.stat.isdir
          - osbuild_worker_config_dir_stat.stat.mode == osbuild_worker_config_dir_mode

    - name: Stat osbuild_worker_config_file
      ansible.builtin.stat:
        path: "{{ osbuild_worker_config_file }}"
      register: osbuild_worker_config_file_stat

    - name: Check that osbuild_worker_config_file exists
      ansible.builtin.assert:
        that:
          - osbuild_worker_config_file_stat.stat.exists
          - osbuild_worker_config_file_stat.stat.isreg
          - osbuild_worker_config_file_stat.stat.mode == osbuild_worker_config_file_mode

    - name: Check status of osbuild remote worker service
      ansible.builtin.systemd:
        name: "{{ osbuild_worker_remote_worker_service_name }}"
      register: osbuild_remote_worker_service

    - name: Check that osbuild remote worker service is enabled and started
      ansible.builtin.assert:
        that:
          - osbuild_remote_worker_service.status['LoadState'] == 'loaded'
          - osbuild_remote_worker_service.status['ActiveState'] == 'active'
          - osbuild_remote_worker_service.status['UnitFileState'] == 'enabled'

    - name: Fetch the content of osbuild worker config file (Base64 encoded)
      ansible.builtin.slurp:
        src: "{{ osbuild_worker_config_file }}"
      register: osbuild_worker_config_file_content_encoded

    - name: Register (raw) content of osbuild worker config file as a variable
      ansible.builtin.set_fact:
        osbuild_worker_config_file_content: "{{ osbuild_worker_config_file_content_encoded.content | b64decode }}"

    - name: Register expected config part as variable
      ansible.builtin.set_fact:
        auth_config_part: |-
          base_path = "{{ test_osbuild_worker_base_path }}"
          deployment_channel = "{{ test_worker_deployment_channel }}"

          [authentication]
          oauth_url = "{{ test_osbuild_worker_authentication_oauth_url }}"
          client_id = "{{ test_osbuild_worker_authentication_client_id }}"
          client_secret = "{{ test_osbuild_worker_authentication_client_secret_path }}"
          offline_token = "{{ test_osbuild_worker_authentication_offline_token_path }}"

    - name: Check the worker config file
      ansible.builtin.assert:
        that:
          - auth_config_part in osbuild_worker_config_file_content
          - osbuild_worker_config_file_content is not match(".*\[aws\].*")
          - osbuild_worker_config_file_content is not match(".*\[azure\].*")
          - osbuild_worker_config_file_content is not match(".*\[gcp\].*")
          - osbuild_worker_config_file_content is not match(".*\[koji.+\].*")

    - name: Stat client_secret file
      ansible.builtin.stat:
        path: "{{ test_osbuild_worker_authentication_client_secret_path }}"
      register: client_secret_file_stat

    - name: Check that client_secret file exists on the remote host
      ansible.builtin.assert:
        that:
          - client_secret_file_stat.stat.exists
          - client_secret_file_stat.stat.isreg
          - client_secret_file_stat.stat.mode == osbuild_worker_secrets_mode

    - name: Stat offline_token file
      ansible.builtin.stat:
        path: "{{ test_osbuild_worker_authentication_offline_token_path }}"
      register: offline_token_file_stat

    - name: Check that offline_token file exists on the remote host
      ansible.builtin.assert:
        that:
          - offline_token_file_stat.stat.exists
          - offline_token_file_stat.stat.isreg
          - offline_token_file_stat.stat.mode == osbuild_worker_secrets_mode
