---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "osbuild-worker-${image:-fedora}-${tag:-latest}"
    image: "${namespace:-quay.io/fedora}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # this scenario is not idempotent due to the force restart
    # - idempotence
    - side_effect
    # use the verify.yml from the default scenario
    - verify ../default/verify.yml
    # instead run the converge once more and verify that the worker was restarted
    - converge
    - verify
    - cleanup
    - destroy
