---
name: Create and push release tag

on:
  workflow_dispatch:
jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Upstream tag
        uses: osbuild/release-action@create-tag
        with:
          token: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
          username: imagebuilder-bot
          email: imagebuilder-bots+imagebuilder-bot@redhat.com
          semver: "true"
